# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  workflow_dispatch:
  workflow_run:
    workflows: [".NET Build"]
    types:
      - completed

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $username -p $password
          
      - name: Build the Docker image
        run: docker build ./SplashStats.API/ --file Dockerfile --tag $username/splashstatsapp:$(date +%s)
      
      - name: Publish to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/splashstatsapp
      
